version: "3"
services: 
  api:
    image: (username)/(repo_name)  # change this!!
    depends_on:
      - postgres
    ports:
      - 80:8000 
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000  
    # env_file:
    #   - ./.env
    # now the env variables are taken from the prod container OS
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    # env_file:
    #   - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db: /var/lib/postgresql/data

volumes:
  postgres-db:
    

# $ docker-compose -f docker-compse-prod.yml up -d
